workflows:
  zara_ios_release:
    name: Zara iOS Release Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_SCHEME: "ZaraBridgePulseApp"
        XCODE_PROJECT: "ZaraBridgePulseApp.xcodeproj"
        APP_VERSION: "1.0.0"
      xcode: 16.4
      cocoapods: default
      node: latest
    scripts:
      - name: Clean previous build
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData || true
          rm -rf build || true
      - name: Set Swift build flags
        script: |
          export SWIFT_VERSION=6.0
          export SWIFT_OPTIMIZATION_LEVEL=-Onone
      - name: Build ZaraBridgePulseApp
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build
    artifacts:
      - build/**/*.ipa
      - build/**/*.xcarchive
    publishing:
      email:
        recipients:
          - "zsolt@example.com"

