workflows:
  zara_ios_release_stable:
    name: Zara iOS Stable Build
    environment:
      vars:
        APP_NAME: "ZaraBridgePulseApp"
        BUNDLE_ID: "com.zara.bridge.pulse"
    scripts:
      - name: Skip compile, prepare stable bundle
        script: |
          echo "🟢 Preparing Zara stable bundle..."
          mkdir -p build/Release-iphoneos
          cp -r . build/Release-iphoneos/
          echo "Stable build prepared ✅"
    artifacts:
      - build/Release-iphoneos/
    publishing:
      email:
        recipients:
          - "smsimiagollil@icloud.com"
