workflows:
  zara_ios_release:
    name: Zara iOS Release (No-XcodeProj)
    max_build_duration: 60
    environment:
      xcode: 16.4
      vars:
        APP_NAME: "ZaraBridgePulseApp"
    scripts:
      - name: Clean workspace
        script: |
          rm -rf .build || true
      - name: Build Swift sources directly
        script: |
          mkdir -p .build
          swiftc -target arm64-apple-ios15.0 \
            -sdk $(xcrun --sdk iphoneos --show-sdk-path) \
            ChatBubbles.swift ChatScene.swift InputBar.swift VisualMirror.swift UnityHook.swift main.swift \
            -o .build/ZaraBridgePulseApp
      - name: Package app
        script: |
          mkdir -p build/ipa
          zip -r build/ipa/ZaraBridgePulseApp.zip .build/ZaraBridgePulseApp
    artifacts:
      - build/ipa/*.zip
    publishing:
      email:
        recipients:
          - "zsolt@example.com"
