workflows:
  zara_ios_release_stable:
    name: Zara iOS Stable Build
    environment:
      vars:
        APP_NAME: "ZaraBridgePulseApp"
        BUNDLE_ID: "com.zara.bridge.pulse"
    scripts:
      - name: Create dummy build artifact
        script: |
          echo "🟢 Creating ZaraBridgePulseApp stable build folder..."
          mkdir -p build/Release-iphoneos
          echo "Zara stable build package ready." > build/Release-iphoneos/README.txt
          echo "✅ Done."
    artifacts:
      - build/Release-iphoneos/
    publishing:
      email:
        recipients:
          - "smsimiagollil@icloud.com"
